### PR TITLE
Mom class tweaked

### PR DESCRIPTION
**Pull request by RAJKUMAR18**
Various new primary functions are added for the ease.More features can be added if required

### CODE REVIEW

**Comment by RAJKUMAR18** [comment]
@stethewwolf please review and let me know

**Comment by stethewwolf** [comment]
Hello, why do not you try to merge your mom class with mine? Ensuring that the program continues to work.
I added the folder sample data did you run the program ?? I updated the main README would you try it  ?? 
which ide are you using ( i' m curious xD )

**Comment by RAJKUMAR18** [comment]
I thought that i would first let you decide whether to merge or not
I use Pycharm as an IDE

**Comment by stethewwolf** [comment]
i commented the file, the functions are not bad , but we need a compare function 0 : ) anyway i use pycharm too . ..  it should be better if we find a proper place where talk about this code ...

**Comment by RAJKUMAR18** [comment]
I will try to find a platform where we can discuss about the code.Also in your code you have yet not implemented inheritance.In my code i have provided a function "data_movement" which can be helpful to implement it in the 'DataMgr' class.

Given that we have all the data stored and persistent only then we can implement the compare function

**Comment by stethewwolf** [comment]
what do you think about jabber  ?? do you can submit issues ?? we can post there ...

**Pull request merged**
